### ISSUE TITLE
3 Gottheiten

### ISSUE THREAD

**Issue by HackerKat** [LB31/ShintoPuzzleGame#11]
- 3 wichtige Gottheiten finden
- sich über deren primären Eigenschaften informieren
- anhand dieser Eigenschaften bzw. passend zu diesen Rätsel formulieren

Potenzielle Götter:
- Inari (Fuchs stuff)
- Hachiman (Kriegsgott guy)
- Izanagi und Izanami (Schöpfungsgötter)
- Amaterasu (Sonnengöttin)
- Susanoo (Sturmgott), Bruder von Amaterasu
- Kagutsuchi (Feuerguy, der die Mutter aus Versehen killte)

**Comment by LB31** [comment]
**Inari**

Göttin für/von/der:
- Füchse
- Fruchtbarkeit
- Reis
- Tee + Sake
- Landwirtschaft
- Industrie
- Wohlstand/Erfolg generell
- Früher auch Beschützerin der Schmiede und Händler

Inaris Symbole:
Wunsche erfüllender Juwel, Füchse/Kitsune, Sichel, Reissack, Garbe, Schwert, manchmal Peitsche

**Geschichte und Ausbreitung**
Wird je nach Region und persönlichem Glauben sowohl weiblich, männlich als auch androgyn dragestellt. Ich behandle sie im weiteren Verlauf mal als Frau.
Wird spätestens seit Errichtung ihres Hauptschreins 771 n. Chr. verehrt, angeblich aber schon seit Ende des 5ten Jahrhunderts. Im 16ten Jahrhundert, wurde sie zur Beschützerin der Kriege, was zu ihrer Ausbreitung in ganz Japan führte.
Im 8teh Jahrundert ernannte der Mönch Kukai Inari zur Verteidigerin des buddhistischen Temples Toji in Kyoto, weswegen sie auch in dieser Religion wichtig ist.
Mehr als 1/3 aller Schreine in Japan (32k) sid Inari gewidmet.

**Kitsune**
Die Kitsune sind Rot- und Eisfüchse. Die weißen sind Inaris Boten. Inari wird oft als ein Kitsune dargestellt, was sowohl shintuistische als auch buddhistische Priester nicht gut finden. 
Wiederum die Kitsune gelten als Hengeyokai (Gestaltwandler), die sich in Menschen, primär Frauen, verwandeln können. Kitsune könen Fruchtbarkeit, aber auch großes Unheil bringen. Außerdem Feuer mit ihrer Schnauze oder Schwanzspitze und Illusionen erzeugen. Fliegen und Besitz von Menschen ergreifen ist auch auf der Skill Liste. Je älter und je mehr Schwänze (max. 9), desto mächter ist ein Kitsune. Kitsune gelten als allgemein gut und können mit Gebeten und Opfergaben bei Laune gehalten werden. 

**Mögliche Rätsel**
- 20 süße Kitsune verwandeln sich jeden Samstag in Menschen und genießen zusammen die in ihrem Schrein erbrachten Opfergaben. 
Diesmal tranken 10 von ihnen guten Sake, 15 aßen leckeren Reis und 3 von ihnen wollten sich lediglich unterhalten.
Wie viele der Kitsune aßen Reis und tranken dazu Sake?
(Mit einem hübschen dazu passenden Bild schmücken; die Antwort wird als einzugebender int erwartet; den Kommentar zur richtigen Antwort mit einer spannenden Info zu Kitsune würzen)

![](https://upload.wikimedia.org/wikipedia/commons/c/c2/Geisha_Playing_the_Hand-Game_Kitsune-ken_%28%E7%8B%90%E6%8B%B3%29%2C_a_Japanese_rock-paper-scissors_variant%2C_by_Kikukawa_Eizan_%28%E8%8F%8A%E5%B7%9D%E8%8B%B1%E5%B1%B1%29.jpg)

- Beim Besuch ihres Hauptschreines Fushimi Inari-Taisha in Kyoto schaut sich Inari die an sie gerichteten Kiganbun (Wunsch-Briefe) an, als die Kitsune ihr plötzlich aufgeregt zurufen, dass eines der Schriftstücke vor ihr ein besonders schöner Liebesbrief ist. 
Um welchen davon handelt es sich wohl?

![rätselLibesbriefFrage](https://user-images.githubusercontent.com/15799249/81461265-f2ab4580-91aa-11ea-8ae4-81e045157923.JPG)
![rätselLibesbriefAntwort](https://user-images.githubusercontent.com/15799249/81461266-f50d9f80-91aa-11ea-949f-cc83ccf2b9c7.JPG)

**Comment by masterwarwolf** [comment]
### Die 3 Götter

kurze Vorgeschichte:
-   blabla

### Amaterasu-o-mi-kami - Amaterasu
![Amaterasu_1](https://user-images.githubusercontent.com/12695383/81473551-89095680-91ff-11ea-98c3-cba79cda3a3e.jpg) 
_https://en.wikipedia.org/wiki/Amaterasu#/media/File:Amaterasu_cave_crop.jpg_



### Geburt 
Nehmen wir:
- Geboren aus dem linken Auge Izanagis, nachdem er sich den "Schmutz/Fluch" der Unterwelt im Fluss Woto abgewaschen hat.
Ihr wurde das Mandat des Himmels gegeben

Alternative (Spiegel Geburt):


### Attribute 
-   Gott der Sonne und des Universum
-   Namensbedeutung: "Am Himmel scheinende große erlauchte Göttin"
-   Weiblich, 1. der noblen Kinder von Izanagi
-   Ältere Schwester von Susanoo und Tsukuyomi
-   geboren aus dem linken Auge Izanagis
-   Berufene Königin des Himmelreiches, Takamagahara (or Takama no Hara)
-   Schöpfergott, als Rolle übernommen von ihrem Vater übernommen, hat nicht das Universum erschaffen, aber ihre Sonne gibt allem Leben
-   Verbannte ihre Geschwister wegen "Verbrechen" aus dem Himmelreich
-   Versteckt sie sich herrscht Dunkelheit / Höhlengeschichte
-   Ihr Enkel Ninigi, ein Kami für Reisanbau, soll die Welt regieren und ist Ahnherr der jap. Kaiser
-   Verbannte Susanoo und Tsukuyomi aus dem Himmelreich, siehe Susanoo und Tsukuyomi
-   eventuell Ehefrau von Tsukuyomi

### Höhlengeschichte
Es gab ein Wettstreit zwischen Amaterasu und Susanoo, bei dem jeder, aus einem Gegenstand des anderen, Götter erschaffen soll. Amaterasu nimmt das Schwert von Susanoo, das Totsuka-no-Tsurugi (Schwert von 10 Handbreiten, damit ist ein spezieller Schwerttyp gemeint) und erschafft daraus 3 Göttinnen. Susanoo nimmt das Band der Halskette Yasakani no Magatama und erschafft daraus 5 Götter. Susanoo verliert und rasend vor Wut rächt er sich, wobei er eine Dienerin Amaterasus tötet, sowie ein Pferd, welches er in einen Weiher wirft und ihre Reisfelder zerstört. Susanoo wird daurafhin aus dem Himmelreich verbannt und Amatarasu versteckt sich wegen der Aktionen ihres Bruders beschämt in einer Höhle im Himmelreich (Ama-no-Iwato - Himmlische Steinhöhle). Da sie sich versteckte, gab es keine Sonne mehr. Die anderen Götter lockten sie aus der Höhle mit einem Spiegel und versperrten dann den Eingang, sodass sie nicht mehr in die Höhle kam. Die Sonne schien wieder.

Bild: Die Götter holen Amaterasu aus der Höhle
![Amaterasu_cave](https://user-images.githubusercontent.com/12695383/81473637-1c428c00-9200-11ea-9fa4-cce6d384aaf8.jpeg)
_https://en.wikipedia.org/wiki/Amaterasu#/media/File:Amaterasu_cave_-_large_-_1856.jpeg_


### Throninsignien Japans
![Amaterasu_Regalia_1](https://user-images.githubusercontent.com/12695383/81474267-83623f80-9204-11ea-90c2-989d05709f1f.jpg)
_https://en.wikipedia.org/wiki/Imperial_Regalia_of_Japan#/media/File:%E4%B8%89%E7%A5%9E%E5%99%A8.png_
-   Kusanagi-no-Tsurugi (Grass-Cutting Sword): Geschenkt von Susanoo als Entschuldigung für ein Verbrechen (siehe Susanoo)
-   Yata no Kagami (The Eight Ta Mirror): Geschmiedet von Ishikori-dome no Mikoto(Spiegel Kami), benutzt um Amaterasu aus der Höhle herauszulocken (Siehe Höhlengeschichte)
-    Yasakani no Magatama (): Tropfenförmige Schmuckstücke die zu einer Halskette gehören, eventuell mit dem Spiegel benutzt um Amaterasu aus der Höhle zu locken. Schutzamulett?

---
### Susanoo-no-Mikoto - Susanoo
![Susanoo_1](https://user-images.githubusercontent.com/12695383/81478222-3d18da80-921c-11ea-96b7-ec6ba551a092.jpg)
https://de.wikipedia.org/wiki/Susanoo#/media/Datei:Dragon_Susanoo_no_mikoto_and_the_water_dragon.jpg

### Geburt
Er entsprang Izanagis Nase, als er sich diese wusch.
Ihm wurde das Mandat des Meeres gegeben.

### Hauptschrein 
Bild - Izumo no Ōyashiro, wörtlich Groß-Schrein von Izumo, sehr alt
![IzumoSchrein_1](https://user-images.githubusercontent.com/12695383/81479156-faf29780-9221-11ea-871d-90852825bbb2.jpg)
https://de.wikipedia.org/wiki/Izumo-Taisha#/media/Datei:Izumo-taisha14bs4592.jpg

### Attribute
-   Jüngster der drei noblen Kinder Izanagis
-   Gott des Sturms und der Meere
-   Verbannt aus dem Himmelreich auf die Erde
-   Ambivalentes Verhalten, hat sowohl viele gute als auch schlechte Taten begannen
-   Bekannter Held, siehe Kampf mit Yamata no Orochi
-   "brachte Menschen Kultur und Zivilisation" -  siehe Prometheus
-   chaotisch, stürmisch, kriegerisch

### Kampf mit Yamata no Orochi
Nachdem Susanoo aus dem Himmelreich verbannt wurde, wanderte er auf der Erde umher. 
Er begegnete einem alten Menschenpaar, die sich beklagten, dass der acht-köpfige Drache Yamata no Orochi sieben der acht Kinder des Pärchens gefressen hatte und angekündigt das letzte Kind zu fressen. 
Er stimmte zu der Familie zu helfen und bestimmte, dass das Paar acht Schalen starken Sake bereitzustellen. Der Drache fiel auf die List rein, wobei jeder Kopf aus einer Schale trank und danach einschlief. Dem schlafenden Drachen schlug Susanoo die Köpfe, sowie die Schwänze ab und im 4. Schwanzstumpf fand er das Schwert Kusanagi-no-Tsurugi, welches er dann als Entschuldigung für sein Verhalten, siehe Amaterasu Höhlengeschichte, an Amaterasu gegeben hat.

---

### Tsukuyomi-no-Mikoto - Tsukuyomi
Bild: Tsukuyomis Abstieg auf die Erde
![Tsukuyomi](https://user-images.githubusercontent.com/12695383/81479190-1fe70a80-9222-11ea-89e6-a2f47e97639f.png)
https://en.wikipedia.org/wiki/Tsukuyomi-no-Mikoto#/media/File:Tsukuyomi-no-mikoto_in_mahoroba.jpg

### Geburt
Er entsprang Izanagis rechten Auge, als er sich dieses wusch.
Ihm wurde das Mandat über den Mond gegeben.

### Hauptschrein
Bild - Schrein auf dem Berg Gassan, Berg des Mondes, Eingeweiht 593 n.Chr.
![Gassan_Schrein_1](https://user-images.githubusercontent.com/12695383/81479002-11e4ba00-9221-11ea-92de-50213e2fe7f6.JPG)
https://en.wikipedia.org/wiki/Gassan_Shrine#/media/File:Gassan_jinja.JPG

### Attribute
-   Gott des Mondes -> Gott der Nacht
-   zweites der noblen Kinder Izanagis
-   in den alten Mythen kaum erwähnt
-   sein Geschlecht ist umstritten, wahrscheinlich männlich
-   eventuell Ehemann von Amaterasu, eventuell geschieden nach Mord an Uke Mocchi
-   ebenfalls aus dem Himmelreich verbannt, siehe Mord an Uke Moch
-   steht für Schönheit, Heiterkeit, Ordnung, Etikette 
-   Etikette ist extrem wichtig, so dass andere Verbrechen für die Einhaltung dieser durchgeführt werden
-   wird eher negativ betrachtet

### Mord an Uke Mochi
Amaterasu bittet Tsukuyomi darum, dass er die Nahrungsgottheit Uke Mochi trifft. Dieser bereitet Tsukuyomi ein Mahl zu, welches er auf unübliche Weise tat. 
Variante 1: in seinem Mund.
Variante 2:
Tsukuyomi war so angewiedert von der Art der Zubereitung, dass er Uke Mochi mit seinem Schwert erstach. Amaterasu war ihrerseits von der Tat Tsukuyomis so angewidert, dass sie nie wieder in Antlitz ihres Bruders sehen wollte. Dadurch entstand Tag und Nacht.
Zusatz 
-   Es gibt nur einen längere Geschichte in der Tsukuyomi auftaucht und das ist diese.
-   In anderen Schriften wird die Ermordung Susanoo zugeschrieben.

---

### Quellen 
https://sumikai.com/japan-erleben/goetter-guide-susanoo-161674/
https://www.isejingu.or.jp/en/about/index.html
https://www.univie.ac.at/rel_jap/kami/Tsukiyomi_no_Mikoto
https://mythology.wikia.org/wiki/Amaterasu
und https://de.wikipedia.org/wiki/ ofc.
