### ISSUE TITLE
Papier Prototyp für Ablaufplan (Welt bauen)

### ISSUE THREAD

**Issue by HackerKat** [LB31/ShintoPuzzleGame#18]
- "Traumwelt" aussehen 
- Design den Gesamtwelt
- Platzierung der Gottheiten (Anzahl)
- Immersiv Wissen vermitteln
- Rätsel platzierung/aussehen
- Interaktion (nur Maus!)

**Comment by masterwarwolf** [comment]
Tutorial: 
- Keine langen Erklärungen, da wenige Modi Operandi vorhanden sind und zu langweilig
- erster Encounter ist fest gescriptet und ist der HelferKami
- HelferKami repräsentiert das Inventar

Inventar / Menü:
- findet im Kopf statt (entsprechende ganz kurze Kamerafahrt)
- Aufbau wie ein 1 Raum Museum, Vergleich: ein 3D Pokedex in dem man sich befindet.
- 2 Verschiedene Lore-Bereiche, Geschichte und Entitäten
- werden nach und nach freigeschaltet mit großen Statuen oder ähnlichen die vorher im Dunkeln sind und später mit Partikeln leuchten, 
- Diese sind, wenn freigeschlatet, anklickbar um mehr Informationen zu bekommen. 
Der HelferKami erzählt immer was dazu


beispiel: aus Hollow Knight 
![Hollowknight_Feind_noch nichtgefunden_Steven](https://user-images.githubusercontent.com/12695383/82728750-b6233200-9cf2-11ea-881a-82f79e8fe335.png)

![Hollowknight_Feind_gefunden_Steven](https://user-images.githubusercontent.com/12695383/82728814-1e721380-9cf3-11ea-974f-e9fa059aa879.png)

Lore ähnlich wie Kami. Eventuell Wandtafeln die dann erleuchtet sind wenn man die entsprechende Lore gefunden hat.

Ideen:
verschieden starke Reinigungsrituale, die man braucht(um Kamis zu exorzieren) um weiter zu kommen, bzw an sich selber anwenden (damit man immuner gegen die "Dunkelheit" wird)

Schematischer Weltaufbau:
![Spielaufbau_Steven](https://user-images.githubusercontent.com/12695383/82728920-b8d25700-9cf3-11ea-8835-059cf49accb9.png)



Rätsel:
2D
SchiebePuzzle aus "Resident Evil 4"
https://www.youtube.com/watch?v=cZa9frufNy0


Zodiac Rätsel aus "Haunted Mansion"
https://www.youtube.com/watch?v=Sz3JESela1M


3D
Licht SpiegelRätsel aus "Rise of the Tomb Raider" ab minute 4

https://www.youtube.com/watch?v=_raCzyAjFeQ
